---
title: "Spike synchrony via cross-correlation"
---

```{r Rmdsetup, echo=FALSE}
# Set max width of markdown code outputs
options(width = 10000)
```

Intro here.

<h2>Load spike rasters</h2>

The first step is to set up the R environment by clearing the workspace, setting a random-number generator seed, and loading the neurons package.

```{r Rsetup}
# Clear the R workspace to start fresh
rm(list = ls())

# Set seed for reproducibility
set.seed(12345) 

# Load neurons package
library(neurons) 
```

```{r load_rasters}
spike.rasters <- read.csv(
  system.file(
      "extdata", 
      "cross_corr_demo_data.csv", 
      package = "neurons"
    )
  )
spike.rasters$genotype <- as.character(spike.rasters$genotype)
print(head(spike.rasters))
```

```{r}

make_trials_by_reference_spikes <- function(
    raster,
    cell_num,
    prespike_time,  # In units of the raster
    postspike_time  # In units of the raster
  ) {
    
    # Subset raster to the penetration of the cell of interest
    raster_p <- raster[raster$recording_name == unique(raster$recording_name[raster$cell == cell_num]), ]
    cell_idx <- which(raster_p$cell == cell_num)
    ref_cell_spikes <- raster_p$time_in_ms[cell_idx]
    
    # Find clear spikes, i.e. spikes surrounded by quiet periods
    ref_cell_spikes_prespike_quiet <- diff(c(0, ref_cell_spikes))
    spikes_preclear <- ref_cell_spikes_prespike_quiet >= prespike_time
    ref_cell_spikes_postspike_quiet <- diff(c(ref_cell_spikes, Inf))
    spikes_postclear <- ref_cell_spikes_postspike_quiet >= postspike_time
    clear_spikes_idx <- cell_idx[spikes_preclear & spikes_postclear]
    
    # Create trial column 
    raster_p$trial <- 0
    
    # Build trial around each clear spike from target cell 
    for (i in seq_along(clear_spikes_idx)) {
      spike_time <- raster_p$time_in_ms[clear_spikes_idx[i]]
      trial_start <- spike_time - prespike_time
      trial_end <- spike_time + postspike_time
      trial_mask <- raster_p$time_in_ms >= trial_start & raster_p$time_in_ms < trial_end
      raster_p$trial[trial_mask] <- i
      raster_p$time_in_ms[trial_mask] <- raster_p$time_in_ms[trial_mask] - spike_time
    }
    
    # Keep only spikes in trials
    raster_p <- raster_p[raster_p$trial > 0, ]
    
    return(raster_p)
  }

trial_duration <- 100 # ms
lag_divider <- 2
bs <- 1.0 # bin size in ms
pre_ratio <- 0.25
ref_cell <- 13
comp_cell <- 15
raster1 <- make_trials_by_reference_spikes(
  raster = spike.rasters,
  cell_num = ref_cell, 
  prespike_time = trial_duration*pre_ratio,
  postspike_time = trial_duration*(1 - pre_ratio)
)

```


```{r}
same_penetration <- function(
    cell_num, 
    raster = spike.rasters
  ) {
    pen <- unique(raster$recording_name[raster$cell == cell_num])
    same_pen <- unique(raster$cell[raster$recording_name == pen])
    return(same_pen)
  }
same_penetration(ref_cell, raster1)

neurons <- load.rasters.as.neurons(
    raster1, 
    bin_size = bs, 
    fallback_duration = trial_duration,
    fallback_displacement = -trial_duration*pre_ratio
  )

cross_corr <- neurons[[paste0("neuron_", ref_cell)]]$compute_crosscorrelation_R(
  neurons[[paste0("neuron_", comp_cell)]], 
  "sum", 
  trial_duration/lag_divider,   # max lag
  TRUE, # use raw?
  TRUE  # verbose?
  )

plot(cross_corr, type='l')

shuffle_spikes <- function(
    raster,
    cell_num
  ) {
    cell_idx <- which(raster$cell == cell_num)
    cell_spikes <- raster$time_in_ms[cell_idx]
    time_range <- range(cell_spikes)
    cell_spikes_shuffled <- runif(
      length(cell_spikes), 
      min = time_range[1], 
      max = time_range[2]
      )
    raster$time_in_ms[cell_idx] <- cell_spikes_shuffled
    return(raster)
  }

raster1_shuffled <- shuffle_spikes(raster1, comp_cell)
neurons_shuffled <- load.rasters.as.neurons(
    raster1_shuffled, 
    bin_size = bs, 
    fallback_duration = trial_duration,
    fallback_displacement = -trial_duration*pre_ratio
  )

cross_corr_shuffled <- neurons_shuffled[[paste0("neuron_", ref_cell)]]$compute_crosscorrelation_R(
  neurons_shuffled[[paste0("neuron_", comp_cell)]], 
  "sum", 
  trial_duration/lag_divider,   # max lag
  TRUE, # use raw?
  TRUE  # verbose?
  )

plot(cross_corr_shuffled, type='l')
#plot(cross_corr - cross_corr_shuffled, type='l')

load_spikes <- function(
    raster,
    cell_num_ref,
    cell_num_comp,
    delay_time 
  ) {
    cell_idx_ref <- which(raster$cell == cell_num_ref)
    cell_idx_comp <- which(raster$cell == cell_num_comp)
    cell_idx_comp <- sample(cell_idx_comp, length(cell_idx_ref)/4, replace = FALSE)
    ref_cell_spikes <- raster$time_in_ms[cell_idx_ref]
    raster$time_in_ms[cell_idx_comp] <- sample(raster$time_in_ms[cell_idx_ref], length(cell_idx_comp), replace = TRUE) + delay_time #+ rnorm(length(cell_idx_comp), 0, 1)
    raster$time_in_ms[cell_idx_comp[1]] <- -trial_duration*pre_ratio 
    raster$time_in_ms[cell_idx_comp[2]] <- trial_duration*(1 - pre_ratio)
    return(raster)
  }

raster1_loaded <- load_spikes(raster1, ref_cell, comp_cell, 5)
neurons_loaded <- load.rasters.as.neurons(
    raster1_loaded, 
    bin_size = bs, 
    fallback_duration = trial_duration,
    fallback_displacement = -trial_duration*pre_ratio
  )

cross_corr_loaded <- neurons_loaded[[paste0("neuron_", ref_cell)]]$compute_crosscorrelation_R(
  neurons_loaded[[paste0("neuron_", comp_cell)]], 
  "sum", 
  trial_duration/lag_divider,   # max lag
  TRUE, # use raw?
  TRUE  # verbose?
  )

plot(cross_corr_loaded, type='l')
#plot(cross_corr - cross_corr_shuffled, type='l')

```



```{r}

test3 <- neurons[[paste0("neuron_", comp_cell)]]$fetch_trial_data_R()
test4 <- neurons_shuffled[[paste0("neuron_", comp_cell)]]$fetch_trial_data_R()
test5 <- neurons_loaded[[paste0("neuron_", comp_cell)]]$fetch_trial_data_R()
testr1 <- neurons[[paste0("neuron_", comp_cell)]]$fetch_spike_raster_R()
testr2 <- neurons_shuffled[[paste0("neuron_", comp_cell)]]$fetch_spike_raster_R()
testr3 <- neurons_loaded[[paste0("neuron_", comp_cell)]]$fetch_spike_raster_R()
hist(testr1[,1])
hist(testr2[,1])
hist(testr3[,1])
plot(rowSums(test3), type='l', col = "blue", ylim = range(c(rowSums(test3), rowSums(test4), rowSums(test5))))
lines(rowSums(test4), col='red')
lines(rowSums(test5), col='green')
ref_test <- neurons[[paste0("neuron_", ref_cell)]]$fetch_trial_data_R()
ref_test_spike <- neurons[[paste0("neuron_", ref_cell)]]$fetch_spike_raster_R()
```

